apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: smile-sales-orders
data:
  default.conf: |
    server {
    listen 80;
    server_name localhost;

    location /static/ {
        alias /data/static/;
    }

    location / {
        proxy_pass http://web-app-service:8000; # Points to the Django web app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
  
  10-listen-on-ipv6-by-default.sh: |
    # Empty script to override the default
