# Generated by Django 5.0.6 on 2024-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_tax_rate_orderitem_tax_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
