# Generated by Django 5.0.6 on 2024-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_abandoned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
