apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  labels:
    type: local
    app: django-staticfiles
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/static"