# Generated by Django 5.0.6 on 2024-06-06 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='original_id',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
