# Generated by Django 5.0.6 on 2024-07-08 12:46

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderitem_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_amount', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('provider_fee')), output_field=models.DecimalField(decimal_places=2, max_digits=16))),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('provider', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=15)),
                ('provider_payment_id', models.CharField(max_length=255, unique=True)),
                ('capture_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', to_field='order_uuid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='original_id')),
            ],
        ),
    ]
