apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: smile-sales-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx-config-map

        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc

      containers:
        - name: nginx
          image: nginx:1.27.1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: default.conf
              name: nginx
              readOnly: true

            - mountPath: "/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh"
              subPath: 10-listen-on-ipv6-by-default.sh
              name: nginx
              readOnly: true

            - mountPath: "/data/static"
              name: staticfiles