apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: smile-sales-orders
  labels:
    app: web-app-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-web-app
  